# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Desafio Orama' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafio Orama
pod 'Alamofire'
pod 'SDWebImage', '~> 5.0'

  target 'Desafio OramaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
